sentences = [
    'Web Development',
    'Machine Learning',
    'Criminal face detection using ML',
    'Discussion Forum',
    'Auto bill generator',
    'Website for visually impaired people',
    'Detection of Manipulated Facial Images',
    'Heart disease prediction',
    '2-D Game using unity engine',
    'Healthcare system DApp using Blockchain',
    'Long term water consumption plan for Mumbai',
    'Credit Card Fraud Detection System',
    'Women safety app',
    'Hand Gesture Calculator',
    'Age and Gender Detection',
    'Parking Management System',
    'Word Prediction System',
    'Diskless Booting',
    'Outcome Prediction For Cricket Matches',
    'Leaf disease detection system',
    'Meal Planning Website',
    'Fake news Classifier',
    'MEDBOT',
    'Image caption generator',
    'FUEL COST PREDICTION',
    'DigiSaatBaara',
    'Real time surveillance',
    'Job Recommendation System',
    'Helmet detection system',
    'Document Digitization',
    'APPLICATION FOR VOTING SYSTEM',
    'College Web Site',
    'Job Prediction',
    'Sentiment Analysis',
    'Video Conferencing',
    'Airport Management and Reservation App',
    'College Web Site',
    'Product Review Sentiment Analysis',
    'Travel Recommander',
    'Farmers Portal',
    'Doodle E- Learning using Deep Learning',
    'Dashboard for Airport Facilities Utilization',
    'Text Summarization',
    'Sign Language converter for Deaf people',
    'Skin cancer detection using ML',
    'Assessing soil parameters for rectification of Crop production and recommendation',
    'Geographical crime rate Prediction Tools',
    'Drug Target Bioactivity prediction',
    'E-commerce with a progressive application of drop shipping',
    'Developer Utility Tool',
    'Online Health Consultancy',
    'Video Summarization in Regional Language',
    'Recommendation of holistic growth of students',
    '2D Simulation of Complex data structures',
    'Competitive coding platform',
    'Prerequisite MOOC course recoomendation based on syllabus',
    'Audio Book Recommender web Application',
    'Distributed Finanaces',
    'Crowd check - over crowd detection and limiting',
    'Email Spam Filtering',
    'AI Virtual Painter',
    'Leaf Disease Detection using CNN',
    'Virtual Interactive Exhibition',
    'E-Learning',
    'Assistance for Dyslexic people',
    'Research Paper Recommendation System',
    'Student Result Management System',
    'Exploratory analysis of geolocational data',
    'Mobile App for Dog care and health Monitor',
    'An Illegal Parking Detection Platform Using Deep Learning',
    'Book Recommendation System',
    'Detection of phising website using Machine Learning',
    'Travel Buddy'
]
